import { fetchAppleHealth, fetchUltraHuman, mockUsageHours } from "@/mocks";
import { uid } from "@/lib/utils";
import { at, todayKey } from "./format";
import type { Domain, TimelineEvent } from "./types";
import { SELF_ID } from "./types";
import { defaultWidgets } from "./widgets";
import { defaultConnectors } from "./connectors";

function ev(
  id: string,
  type: string,
  source_tab: TimelineEvent["source_tab"],
  actor_id: string,
  payload: Record<string, unknown>,
  hoursAgo: number,
  links: string[] = [],
): TimelineEvent {
  return {
    id,
    type,
    source_tab,
    actor_id,
    payload,
    links,
    timestamp: Date.now() - hoursAgo * 3600_000,
  };
}

export function buildSeed(): Domain {
  const day = todayKey();
  const apple = fetchAppleHealth();
  const ultra = fetchUltraHuman();

  const timeline: TimelineEvent[] = [
    ev("ev-sleep", "health.stream.sync", "health", SELF_ID, { source: "ultrahuman", stress: 78, sleep: 5.5 }, 0.4),
    ev("ev-checkin", "health.checkin.save", "health", SELF_ID, { mood: 2, energy: 2, anxiety: 4, stress: 4, sleepHours: 5.6 }, 0.6),
    ev("ev-doctor", "health.note.add", "health", "drshah", { title: "Ferritin follow-up", id: "rec-ferritin" }, 18),
    ev("ev-workout", "health.workout.save", "health", "meera", { title: "Lower-body block" }, 26),
    ev("ev-remind-wo", "work.reminder.add", "work", "meera", { title: "Strength · lower 7:00p", id: "rem-wo" }, 26, ["ev-workout"]),
    ev("ev-peptide", "health.peptide.save", "health", SELF_ID, { vialId: "vial-bpc", name: "BPC-157" }, 72),
    ev("ev-deep", "work.calendar.propose", "work", SELF_ID, { title: "Deep work · Q3 forecast", shortened: true }, 14),
    ev("ev-vendor", "work.calendar.propose", "work", "arjun", { title: "Vendor call", status: "pending" }, 4),
    ev("ev-mag", "shop.buy", "shopping", "priya", { name: "Magnesium glycinate", protocol: true }, 96),
    ev("ev-income", "finance.income", "finance", SELF_ID, { amountInr: 82000, accountId: "acc-media" }, 30),
    ev("ev-loan-nudge", "finance.loan.nudge", "finance", SELF_ID, { loanId: "loan-media" }, 30, ["ev-income"]),
    ev("ev-fare", "travel.watch", "travel", SELF_ID, { tripId: "trip-blr", drop: 1240 }, 8),
    ev("ev-bill", "finance.bill.due", "finance", SELF_ID, { id: "bill-help" }, 2),
    ev("ev-pack", "shop.item.add", "shopping", SELF_ID, { list: "Bangalore packing", fromTravel: true }, 20),
  ];

  return {
    people: [
      { id: SELF_ID, name: "Rajan Malhotra", shortName: "You", circle: "self", title: "Owner", initials: "RM" },
      { id: "anaya", name: "Anaya Malhotra", shortName: "Anaya", circle: "family", title: "Daughter", initials: "AM" },
      { id: "priya", name: "Priya Malhotra", shortName: "Priya", circle: "family", title: "Partner", initials: "PM" },
      { id: "arjun", name: "Arjun Khanna", shortName: "Arjun", circle: "coworkers", title: "Co-worker", initials: "AK" },
      { id: "kabir", name: "Kabir Singh", shortName: "Kabir", circle: "friends", title: "Friend", initials: "KS" },
      { id: "meera", name: "Meera Rao", shortName: "Meera", circle: "trainers", title: "Trainer", initials: "MR", email: "meera@strength.studio", phone: "9810022233", inviteStatus: "accepted" },
      { id: "drshah", name: "Dr. Nisha Shah", shortName: "Dr. Shah", circle: "doctors", title: "Physician", initials: "NS", email: "nisha.shah@clinic.in", inviteStatus: "accepted" },
      {
        id: "p-kiran",
        name: "Kiran Mehta",
        shortName: "Kiran",
        circle: "accountants",
        title: "Accountant",
        initials: "KM",
        email: "kiran@mehtaca.in",
        phone: "9810099001",
        inviteStatus: "pending",
        inviteChannel: "email",
        invitedAt: Date.now() - 26 * 3600_000,
        scopes: [
          { tab: "finance", access: "edit" },
          { tab: "businesses", access: "view" },
        ],
      },
    ],
    timeline,
    calendar: [
      {
        id: "cal-mobility",
        title: "Morning mobility",
        start: at(7, 30),
        end: at(7, 50),
        ownerId: SELF_ID,
        kind: "workout",
        status: "confirmed",
        invitedBy: "meera",
      },
      {
        id: "cal-deep",
        title: "Deep work · Q3 forecast",
        start: at(9, 0),
        end: at(10, 15),
        ownerId: SELF_ID,
        kind: "focus",
        status: "confirmed",
        deepWork: true,
        shortened: true,
        lightened: true,
        note: "Cut from 9–11. Sleep 5.6h + high stress.",
      },
      {
        id: "cal-stand",
        title: "Standup",
        start: at(11, 0),
        end: at(11, 25),
        ownerId: SELF_ID,
        kind: "meeting",
        status: "confirmed",
        invitedBy: "arjun",
      },
      {
        id: "cal-lunch",
        title: "Lunch buffer",
        start: at(12, 30),
        end: at(13, 0),
        ownerId: SELF_ID,
        kind: "personal",
        status: "confirmed",
      },
      {
        id: "cal-vendor",
        title: "Vendor call · Northwind",
        start: at(14, 0),
        end: at(14, 45),
        ownerId: SELF_ID,
        kind: "meeting",
        status: "pending",
        invitedBy: "arjun",
      },
      {
        id: "cal-pickup",
        title: "Pickup Anaya",
        start: at(16, 30),
        end: at(17, 0),
        ownerId: SELF_ID,
        kind: "personal",
        status: "confirmed",
      },
      {
        id: "cal-strength",
        title: "Strength · lower",
        start: at(19, 0),
        end: at(20, 0),
        ownerId: SELF_ID,
        kind: "workout",
        status: "pending",
        invitedBy: "meera",
      },
      {
        id: "cal-anaya-pta",
        title: "School play rehearsal",
        start: at(15, 0),
        end: at(16, 0),
        ownerId: "anaya",
        kind: "personal",
        status: "confirmed",
      },
    ],
    tasks: [
      { id: "task-tiny-1", title: "Reply to school diary note", done: false, ownerId: SELF_ID, createdBy: SELF_ID, priority: 1, tiny: true, due: at(12, 0) },
      { id: "task-tiny-2", title: "Ping Patel on overdue invoice", done: false, ownerId: SELF_ID, createdBy: SELF_ID, priority: 1, tiny: true, due: at(13, 0) },
      { id: "task-3", title: "Rewrite Northwind campaign brief", done: false, ownerId: SELF_ID, createdBy: "arjun", priority: 2 },
      { id: "task-4", title: "Board deck — Q3 narrative", done: false, ownerId: SELF_ID, createdBy: SELF_ID, priority: 2 },
      { id: "task-5", title: "File GST backup folder", done: false, ownerId: SELF_ID, createdBy: SELF_ID, priority: 3 },
      { id: "task-anaya", title: "Pack art supplies for Saturday", done: false, ownerId: "anaya", createdBy: SELF_ID, priority: 2, tiny: true },
    ],
    emails: [
      {
        id: "em-1",
        from: "arjun@malhotramedia.in",
        fromName: "Arjun Khanna",
        subject: "Vendor call at 2 — can you take it?",
        preview: "Northwind wants to walk the Q4 media mix. I put a hold on your calendar.",
        body: "Rajan — Northwind wants to walk the Q4 media mix today at 2. I dropped a hold on your calendar. Accept if you can own it; I'll join mute.\n\nArjun",
        timestamp: at(8, 12),
        unread: true,
        mailbox: "work",
      },
      {
        id: "em-2",
        from: "payroll@malhotramedia.in",
        fromName: "Payroll",
        subject: "Contractor payouts ready",
        preview: "Three invoices queued. Confirm before 4pm.",
        body: "Three contractor invoices are queued for today. Confirm in Businesses before 4pm IST.",
        timestamp: at(7, 40),
        unread: true,
        mailbox: "work",
      },
      {
        id: "em-3",
        from: "office@dpsnoida.edu.in",
        fromName: "DPS Noida",
        subject: "Anaya · parent note",
        preview: "Please acknowledge the Saturday rehearsal change.",
        body: "Dear Parent, Saturday rehearsal moves to 10:00. Please acknowledge via the school diary.",
        timestamp: at(7, 5),
        unread: true,
        mailbox: "personal",
      },
      {
        id: "em-4",
        from: "alerts@indigo.in",
        fromName: "IndiGo",
        subject: "DEL–BLR fare dropped ₹1,240",
        preview: "Your watched 16 Sep morning flight is cheaper.",
        body: "Watched trip Bangalore 16 Sep. 6:55am DEL–BLR is ₹1,240 cheaper than yesterday.",
        timestamp: at(6, 50),
        unread: false,
        mailbox: "personal",
      },
    ],
    reminders: [
      { id: "rem-wo", title: "Strength · lower", when: at(18, 45), ownerId: SELF_ID, createdBy: "meera", fired: true },
      { id: "rem-school", title: "Leave for pickup", when: at(16, 10), ownerId: SELF_ID, createdBy: SELF_ID, fired: false },
      { id: "rem-mag", title: "Evening supplements", when: at(21, 0), ownerId: SELF_ID, createdBy: SELF_ID, fired: false },
    ],
    notifications: [
      {
        id: "n-mag",
        kind: "adherence",
        title: "Did you take this?",
        body: "Magnesium glycinate 400mg is still open on today's protocol.",
        timestamp: at(8, 0),
        read: false,
        tab: "home",
      },
      {
        id: "n-vendor",
        kind: "confirmation",
        title: "Accept vendor call?",
        body: "Arjun invited you to Northwind at 2:00. Not silent — confirm in-app.",
        timestamp: at(8, 12),
        read: false,
        tab: "work",
        action: { label: "Accept", eventType: "work.calendar.accept", payload: { id: "cal-vendor" } },
      },
      {
        id: "n-strength",
        kind: "confirmation",
        title: "Trainer slot",
        body: "Meera proposed Strength · lower at 7:00p. Calendar still needs your confirm.",
        timestamp: Date.now() - 26 * 3600_000,
        read: false,
        tab: "work",
        action: { label: "Accept", eventType: "work.calendar.accept", payload: { id: "cal-strength" } },
      },
      {
        id: "n-fare",
        kind: "alert",
        title: "Bangalore fare drop",
        body: "Watched DEL–BLR 16 Sep is ₹1,240 cheaper.",
        timestamp: at(6, 50),
        read: false,
        tab: "travel",
      },
      {
        id: "n-loan",
        kind: "nudge",
        title: "Settle the media loan?",
        body: "₹82,000 landed in Malhotra Media. You are owed ₹1,50,000.",
        timestamp: Date.now() - 30 * 3600_000,
        read: true,
        tab: "finance",
      },
      {
        id: "n-help",
        kind: "reminder",
        title: "House help salary due today",
        body: "₹18,000 · queue pay or mark paid.",
        timestamp: at(7, 0),
        read: false,
        tab: "finance",
        action: { label: "Queue", eventType: "finance.bill.queue", payload: { id: "bill-help" } },
      },
    ],
    suggestions: [],
    dismissedSuggestionIds: [],
    adherence: [
      { id: "adh-mag", name: "Magnesium glycinate", kind: "supplement", dose: "400mg evening", taken: false, missed: false },
      { id: "adh-d", name: "Vitamin D3", kind: "supplement", dose: "5000 IU", taken: false, missed: false },
      { id: "adh-omega", name: "Omega-3", kind: "supplement", dose: "2g with lunch", taken: true, missed: false },
      { id: "adh-bpc", name: "BPC-157", kind: "peptide", dose: "250 mcg · 10 units", taken: false, missed: false, vialId: "vial-bpc" },
    ],
    vials: [
      {
        id: "vial-bpc",
        name: "BPC-157",
        powderMg: 5,
        vialVolumeMl: 2,
        syringeVolumeMl: 1,
        syringeUnits: 100,
        targetDoseMcg: 250,
        startDate: at(8, 0, -12),
        history: [
          { date: todayKey(at(8, 0, -2)), taken: true },
          { date: todayKey(at(8, 0, -1)), taken: true },
          { date: day, taken: false },
        ],
      },
    ],
    records: [
      {
        id: "rec-cbc",
        kind: "lab",
        title: "CBC + ferritin",
        date: at(9, 0, -8),
        summary: "Hb 12.1 · Ferritin 28 µg/L (low). Repeat in 6 weeks. Do not start iron without the repeat.",
        authorId: "drshah",
      },
      {
        id: "rec-rx",
        kind: "prescription",
        title: "Rx · Mag + D3",
        date: at(9, 30, -8),
        summary: "Magnesium glycinate 400mg HS. Vitamin D3 5000 IU daily × 8 weeks.",
        authorId: "drshah",
      },
      {
        id: "rec-ferritin",
        kind: "note",
        title: "Ferritin follow-up",
        date: at(18, 10, -1),
        summary: "Discussed energy dip. Observational only — no new prescription. Watch GI symptoms if they self-start heme iron.",
        authorId: "drshah",
      },
      {
        id: "rec-uh",
        kind: "upload",
        title: "UltraHuman weekly PDF",
        date: at(7, 0, -1),
        summary: "Recovery 41. Strain high on Tue/Wed. Sleep debt 3.4h.",
        authorId: SELF_ID,
      },
    ],
    workout: {
      id: "wp-1",
      title: "Hypertrophy · 4-day",
      trainerId: "meera",
      notes: "Keep RPE 7. If sleep < 6.5h, drop the last set. No guilt — just shorter.",
      days: [
        { day: "Thu", focus: "Lower", exercises: [{ name: "Goblet squat", sets: "3×8" }, { name: "RDL", sets: "3×8" }, { name: "Split squat", sets: "2×8" }] },
        { day: "Sat", focus: "Upper", exercises: [{ name: "DB press", sets: "3×8" }, { name: "Row", sets: "3×10" }, { name: "Face pull", sets: "2×15" }] },
        { day: "Mon", focus: "Posterior", exercises: [{ name: "Hip thrust", sets: "3×8" }, { name: "Walk lunge", sets: "2×10" }] },
      ],
    },
    diet: [
      { id: "d-bf", slot: "breakfast", title: "Eggs + greek yogurt", notes: "Protein before 10. Skip the heme iron." },
      { id: "d-ln", slot: "lunch", title: "Chicken thighs + spinach", notes: "Omega-3 with this meal. Ferritin-aware, not a new protocol." },
      { id: "d-dn", slot: "dinner", title: "Dal + rice, light", notes: "Magnesium 400mg after. No late caffeine." },
    ],
    checkins: [
      { date: day, mood: 2, energy: 2, anxiety: 4, sleepHours: 5.6, stress: 4, notes: "Wired-tired. Short with Anaya at breakfast." },
      { date: todayKey(at(8, 0, -1)), mood: 3, energy: 3, anxiety: 3, sleepHours: 6.8, stress: 3 },
      { date: todayKey(at(8, 0, -2)), mood: 4, energy: 4, anxiety: 2, sleepHours: 7.1, stress: 2 },
    ],
    metrics: [
      { date: todayKey(at(8, 0, -1)), weightKg: 76.4, waistCm: 86 },
      { date: todayKey(at(8, 0, -8)), weightKg: 76.9, waistCm: 87 },
    ],
    streams: [
      { ...apple, syncedAt: Date.now() - 12 * 60_000 },
      { ...ultra, syncedAt: Date.now() - 6 * 60_000 },
    ],
    usageByHour: mockUsageHours(),
    growth: [
      { id: "g-spirit", area: "spirituality", title: "Morning sit", streak: 12, lastDone: todayKey(at(6, 30, -1)) },
      { id: "g-read", area: "readings", title: "Meditations · Book 4", streak: 4, lastDone: todayKey(at(22, 0, -1)) },
      { id: "g-pod", area: "podcasts", title: "Huberman Lab", streak: 2, lastDone: todayKey(at(18, 0, -3)) },
      { id: "g-hobby", area: "hobbies", title: "Film photography", streak: 1, lastDone: todayKey(at(16, 0, -6)) },
    ],
    chat: [
      {
        id: "ch-1",
        role: "user",
        text: "Something short for high stress. Not a lecture.",
        timestamp: Date.now() - 50 * 60_000,
      },
      {
        id: "ch-2",
        role: "bot",
        text: "From your subscriptions: a 10-minute Yoga Nidra and a stillness playlist. Logged to the timeline. Home can drop the sit onto the calendar.",
        timestamp: Date.now() - 49 * 60_000,
        results: [
          { title: "Yoga Nidra — 10 minutes", source: "youtube", meta: "Ally Boothroyd · subscribed" },
          { title: "Music for Inner Stillness", source: "spotify", meta: "In your library" },
        ],
      },
    ],
    trips: [
      {
        id: "trip-blr",
        mode: "work",
        title: "Bangalore client",
        destination: "Bengaluru",
        start: at(6, 55, 6),
        end: at(21, 0, 8),
        status: "watching",
        rateWatch: { current: 6840, previous: 8080, label: "DEL–BLR 16 Sep 6:55" },
        estimateInr: 22000,
        packing: ["Blazer", "Charger", "BPC-157 travel case", "Presentation clicker"],
      },
      {
        id: "trip-beach",
        mode: "personal",
        title: "October with Anaya",
        vibe: "beach",
        companions: "Anaya",
        season: "October",
        budgetInr: 120000,
        destination: "Gokarna",
        status: "suggested",
        estimateInr: 98000,
        itinerary: [
          { day: 1, title: "Arrive + Om Beach", detail: "IndiGo to GOX, cab to homestay, sunset swim." },
          { day: 2, title: "Kudle + temple", detail: "Morning walk, Mahabaleshwar temple, slow lunch." },
          { day: 3, title: "Half-day boat", detail: "Half moon beach. Buffer day if energy is low." },
        ],
      },
    ],
    lists: [
      {
        id: "list-groc",
        name: "Groceries",
        shared: true,
        items: [
          { id: "gi-1", name: "Eggs", qty: "2 dozen", ownerId: "priya", checked: false },
          { id: "gi-2", name: "Bananas", qty: "1 kg", ownerId: "anaya", checked: true },
          { id: "gi-3", name: "Greek yogurt", qty: "4 cups", ownerId: SELF_ID, checked: false, fromProtocol: true },
          { id: "gi-4", name: "Spinach", qty: "2 bunches", ownerId: "priya", checked: false },
          { id: "gi-5", name: "Oat milk", qty: "1 L", ownerId: "anaya", checked: false },
          { id: "gi-6", name: "Chicken thighs", qty: "1 kg", ownerId: SELF_ID, checked: false },
        ],
      },
      {
        id: "list-pack",
        name: "Bangalore packing",
        shared: false,
        items: [
          { id: "pi-1", name: "Blazer", qty: "1", checked: false, fromTravel: true },
          { id: "pi-2", name: "BPC-157 travel case", qty: "1", checked: false, fromTravel: true, fromProtocol: true },
          { id: "pi-3", name: "Charger", qty: "1", checked: true, fromTravel: true },
        ],
      },
    ],
    research: [
      {
        id: "res-stereo",
        category: "Music system",
        name: "KEF LSX II LT",
        notes: "Vs. Audioengine A5+. Need for the study, not the hall.",
        priceInr: 84000,
        lastPriceInr: 89000,
        relevantToHealth: false,
      },
      {
        id: "res-iron",
        category: "Protocol",
        name: "Heme iron bisglycinate",
        notes: "Doctor said wait for repeat ferritin. Keep in vault only.",
        priceInr: 1890,
        lastPriceInr: 1890,
        relevantToHealth: true,
      },
    ],
    inventory: [
      { id: "inv-mag", name: "Magnesium glycinate", qty: 60, purchasedAt: Date.now() - 96 * 3600_000, healthProtocol: true },
      { id: "inv-d", name: "Vitamin D3 5000", qty: 90, purchasedAt: Date.now() - 20 * 24 * 3600_000, healthProtocol: true },
    ],
    notes: [
      {
        id: "note-1",
        title: "Doctor visit 2 Sep",
        body: "Ferritin 28. Repeat before iron. Linked to the lab event.",
        createdAt: at(19, 0, -8),
        updatedAt: at(19, 0, -8),
        authorId: SELF_ID,
        shared: false,
        linkedEventIds: ["ev-doctor"],
      },
      {
        id: "note-2",
        title: "Saturday with Anaya",
        body: "Lodhi + ice cream + Midland. She wants the camera.",
        createdAt: at(21, 0, -2),
        updatedAt: at(21, 0, -2),
        authorId: SELF_ID,
        shared: true,
        linkedEventIds: [],
      },
      {
        id: "note-3",
        title: "Voice memo · commute",
        body: "Placeholder. ‘Ask Meera to shorten Thursday if HRV stays low.’",
        createdAt: at(9, 40, -1),
        updatedAt: at(9, 40, -1),
        authorId: SELF_ID,
        shared: false,
        linkedEventIds: [],
        voicePlaceholder: true,
      },
    ],
    accounts: [
      { id: "acc-check", name: "HDFC checking", kind: "personal", balanceInr: 84240 },
      { id: "acc-save", name: "HDFC savings", kind: "personal", balanceInr: 210000 },
      { id: "acc-media", name: "Malhotra Media ops", kind: "business", businessId: "biz-media", balanceInr: 482000 },
    ],
    txns: [
      { id: uid("tx"), accountId: "acc-check", amountInr: -1240, merchant: "BigBasket", category: "grocery", timestamp: at(20, 10, -1) },
      { id: uid("tx"), accountId: "acc-check", amountInr: -2680, merchant: "Uber", category: "transport", timestamp: at(18, 40, -1) },
      { id: uid("tx"), accountId: "acc-check", amountInr: -890, merchant: "Natural Ice Cream", category: "dining", timestamp: at(16, 20, -2) },
      { id: uid("tx"), accountId: "acc-check", amountInr: -4500, merchant: "Apollo Pharmacy", category: "health", timestamp: at(11, 0, -3) },
      { id: uid("tx"), accountId: "acc-check", amountInr: -1899, merchant: "Jio", category: "phone", timestamp: at(9, 0, -5) },
      { id: uid("tx"), accountId: "acc-check", amountInr: -6200, merchant: "Amazon", category: "shopping", timestamp: at(21, 0, -6) },
      { id: uid("tx"), accountId: "acc-media", amountInr: 82000, merchant: "Northwind retainer", category: "income", timestamp: Date.now() - 30 * 3600_000 },
      { id: uid("tx"), accountId: "acc-media", amountInr: -24000, merchant: "Meta ads", category: "ads", timestamp: at(10, 0, -2) },
    ],
    bills: [
      { id: "bill-phone", name: "Jio Fiber + mobile", kind: "phone", amountInr: 1899, dueDay: 5, trend: [1899, 1899, 1999, 1899, 1899, 1899], status: "paid" },
      { id: "bill-electric", name: "BSES electricity", kind: "electricity", amountInr: 3840, dueDay: 12, trend: [2900, 3100, 3600, 4100, 3980, 3840], status: "due" },
      { id: "bill-help", name: "House help salary", kind: "house_help", amountInr: 18000, dueDay: 10, trend: [16000, 16000, 17000, 18000, 18000, 18000], status: "due" },
      { id: "bill-sal", name: "Contractor · design", kind: "salary", amountInr: 45000, dueDay: 25, trend: [45000, 45000, 45000, 48000, 45000, 45000], status: "paid" },
    ],
    loans: [
      { id: "loan-media", from: "me", to: "biz-media", amountInr: 150000, note: "Working-capital float, Jan 2026" },
    ],
    businesses: [
      {
        id: "biz-media",
        name: "Malhotra Media",
        revenueInr: 640000,
        expensesInr: 218000,
        clients: [
          { id: "cl-1", name: "Northwind", status: "retainer" },
          { id: "cl-2", name: "Saffron Goods", status: "project" },
          { id: "cl-3", name: "Pali Studio", status: "paused" },
        ],
        campaigns: [
          {
            id: "cmp-1",
            name: "Northwind — Search Q3",
            spend: 42000,
            impressions: 380000,
            conversions: 28,
            cpl: 1500,
            baselineCpl: 980,
          },
          {
            id: "cmp-2",
            name: "Saffron — Prospecting",
            spend: 18000,
            impressions: 210000,
            conversions: 22,
            cpl: 818,
            baselineCpl: 900,
          },
        ],
      },
    ],
    locations: [
      { personId: "anaya", lat: 28.568, lng: 77.325, label: "DPS Noida", updatedAt: Date.now() - 8 * 60_000 },
      { personId: "priya", lat: 28.567, lng: 77.227, label: "Defence Colony market", updatedAt: Date.now() - 22 * 60_000 },
    ],
    captures: [
      {
        id: "cap-1",
        text: "https://www.youtube.com/watch?v=gokarna-walk — save as research for Travel",
        targetTab: "travel",
        timestamp: Date.now() - 5 * 3600_000,
        actorId: SELF_ID,
      },
    ],
    folders: [
      { id: "fld-inbox", name: "Inbox", parentId: null, createdAt: at(9, 0, -20) },
      { id: "fld-health", name: "Health", parentId: null, createdAt: at(9, 0, -18) },
      { id: "fld-labs", name: "Labs", parentId: "fld-health", createdAt: at(9, 0, -18) },
      { id: "fld-work", name: "Work", parentId: null, createdAt: at(9, 0, -16) },
      { id: "fld-travel", name: "Travel", parentId: null, createdAt: at(9, 0, -14) },
      { id: "fld-personal", name: "Personal", parentId: null, createdAt: at(9, 0, -12) },
    ],
    files: [
      {
        id: "vf-ferritin",
        name: "Ferritin-panel-2Sep.pdf",
        mime: "application/pdf",
        size: 184320,
        folderId: "fld-labs",
        createdAt: at(19, 0, -8),
        textExcerpt: "Ferritin 28 ng/mL. Repeat before iron. Watch GI if self-starting heme.",
        sourceTab: "health",
        exchangeId: "ex-1",
      },
      {
        id: "vf-q3",
        name: "Q3-forecast-draft.md",
        mime: "text/markdown",
        size: 12480,
        folderId: "fld-work",
        createdAt: at(10, 0, -3),
        textExcerpt: "Northwind retainer + Saffron project. Deep work Thursday. Vendor call still pending.",
        sourceTab: "work",
      },
      {
        id: "vf-blr",
        name: "BLR-itinerary.md",
        mime: "text/markdown",
        size: 4096,
        folderId: "fld-travel",
        createdAt: at(8, 0, -1),
        textExcerpt: "DEL–BLR 16 Sep 6:55. Pack blazer, peptide travel case, clicker.",
        sourceTab: "travel",
      },
    ],
    exchanges: [
      {
        id: "ex-1",
        tab: "health",
        channel: "voice",
        title: "Ferritin follow-up",
        query: "Remind me what Dr Shah said about ferritin.",
        response:
          "Ferritin 28. Repeat the panel before starting iron. She flagged GI symptoms if you self-start heme. The lab PDF is in Files → Health → Labs.",
        timestamp: Date.now() - 40 * 60_000,
        actorId: SELF_ID,
        fileIds: ["vf-ferritin"],
      },
      {
        id: "ex-2",
        tab: "work",
        channel: "text",
        title: "Vendor call still pending",
        query: "Is the vendor call confirmed?",
        response:
          "No. Arjun proposed it — it still needs your confirm on Work. Deep work for the Q3 forecast is shortened today.",
        timestamp: Date.now() - 2 * 3600_000,
        actorId: SELF_ID,
        fileIds: [],
      },
      {
        id: "ex-3",
        tab: "travel",
        channel: "file",
        title: "Bangalore packing",
        query: "File this itinerary and tell me what to pack.",
        response:
          "Filed to Travel. Pack the blazer, charger, BPC-157 travel case, and the clicker. Fare watch is still live on DEL–BLR.",
        timestamp: Date.now() - 6 * 3600_000,
        actorId: SELF_ID,
        fileIds: ["vf-blr"],
      },
    ],
    shortcuts: [
      { id: "sc-gym", phrase: "gym", command: "Go to health" },
      { id: "sc-salary", phrase: "salary", command: "Queue house help" },
      { id: "sc-pack", phrase: "pack", command: "Packed the blazer" },
    ],
    homeLayout: "board",
    widgets: defaultWidgets(),
    connectors: defaultConnectors(),
    waThreads: [],
  };
}
